baseURL: "https://aleckzu.github.io/"
title: "Алексей Зубков"
theme: [hugo-PaperMod]

defaultContentLanguage: ru
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["posts"]

# Инструкция для Hugo: создавать поисковый индекс в формате JSON
outputs:
  home:
    - HTML
    - RSS
    - JSON

languages:
  ru:
    languageName: "Русский"
    weight: 1
    menu:
      main:
        - name: Архив
          url: archives
          weight: 5
        - name: Поиск
          url: search/
          weight: 10
        - name: Теги
          url: tags/
          weight: 15

params:
  env: production
  author: Алексей Зубков
  description: "Личный блог Алексея Зубкова"
  defaultTheme: auto
  ShowShareButtons: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true

  # Настройки для работы поиска (алгоритм Fuse.js)
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

  socialIcons:
    - name: github
      url: "https://github.com/aleckzu"
    - name: telegram
      url: "https://t.me/твой_логин"

  profileMode:
    enabled: true
    title: "Алексей Зубков"
    subtitle: "Размышления и мысли"
    imageUrl: "images/Gemini_Generated_Image_.png"
    imageTitle: "Логотип AZ"
    imageWidth: 150
    imageHeight: 150
    buttons:
      - name: "Читать статьи"
        url: "posts"

  assets:
    disableHLJS: true

markup:
  goldmark:
    renderer:
      unsafe: true
